Update `CODEOWNERS` to use `documentation` group [DOC-256]
hazelcast/jdbc-driver-docs pull request #4
Opened 2024-11-19 23:50 UTC by JackPGreen

Ensure consistency across all doc repos

Fixes: [DOC-256](https://hazelcast.atlassian.net/browse/DOC-256)

2024-12-02 09:19 UTC, JackPGreen commented
@oliverhowell are you able to review, please?

2024-12-09 12:22 UTC, oliverhowell requested changes

2024-12-09 12:22 UTC, oliverhowell commented on .github/CODEOWNERS
> +* @hazelcast/documentation
Is there an error signified here? Just wondering if we have the right teams/accounts with admin rights for this repo (I don't)

2024-12-09 12:25 UTC, oliverhowell approved these changes

2024-12-09 12:25 UTC, merged